### ISSUE TITLE
contact | Qinng

### ISSUE THREAD

**Issue by qingwave** [qingwave/qingwave.github.io#33]
https://qingwave.github.io/contact/ 

 畅所欲言 在这里可以留下你的足迹！          document.querySelectorAll('.github-emoji')           .forEach(el =&gt; {             if (!el.dataset.src) { return; }             const img = document.createElement('img');

**Comment by qingwave** [comment]
Professional

**Comment by shiyajuan123** [comment]
> @qingwave
> Professional
two face!

**Comment by shiyajuan123** [comment]
测试一下你的破留言板

**Comment by yuzhiquan** [comment]
你俩玩的挺嗨啊 @qingwave @shiyajuan123
